services:
  mysql:
    image: mysql:8.0
    container_name: 1kulte-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - 1kulte-network
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer:latest
    container_name: 1kulte-adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - 1kulte-network

volumes:
  mysql_data:
    driver: local

networks:
  1kulte-network:
    driver: bridge
